apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: authentication  
#       annotations: 
#         date: "+%H:%M:%S %d/%m/%y"
    spec:     # pod spec
      imagePullSecrets:
      - name: jfrog-secret
      containers: 
      - name: authentication
        #image: deepthi/login-docker:latest # image we pushed
        image: sreyo.jfrog.io/dd-docker-dev-local/login-docker:latest # image we pushed
        
        #imagePullPolicy: Never
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: mongo-root-username
        - name: MONGO_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: secret
              key: mongo-root-password
        - name: ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: secret
              key: auth-token      
        - name: MONGO_HOSTNAME
          valueFrom: 
            configMapKeyRef:
              name: app-configmap
              key: database_hostname
        - name: MONGO_PORT
          valueFrom: 
            configMapKeyRef:
              name: app-configmap
              key: database_port
        - name: MONGO_DB
          valueFrom: 
            configMapKeyRef:
              name: app-configmap
              key: database_db
        #- name: HOSTNAME
          #valueFrom: 
            #configMapKeyRef:
              #name: app-configmap
              #key: list_hostname
        - name: PORT
          valueFrom: 
            configMapKeyRef:
              name: app-configmap
              key: list_port       
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  labels:
    app: authentication
spec:
  selector:
    app: authentication 
  ports:
    - port: 3000
      targetPort: 3000
